name: release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare artifacts
        run: |
          mkdir -p dist
          cp bin/dx dist/dx
          (cd dist && sha256sum dx > dx.sha256)

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/dx
            dist/dx.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
